export const KAFKA_TOPICS = {
    PROJECT: 'project-events',
    PROJECT_MEMBER: 'project-member-events',
    PROJECT_TEAM: 'project-team-events',
    PROJECT_TEAM_MEMBER: 'project-team-member-events',
    PROJECT_TASK: 'project-task-events',
    PROJECT_TASK_TRIGGER: 'project-task-trigger-events',
} as const;

export const KAFKA_EVENTS = {
    PROJECT: { CREATED: 'PROJECT_CREATED', DELETED: 'PROJECT_DELETED' },
    PROJECT_MEMBER: {
        ADDED: 'PROJECT_MEMBER_ADDED',
        DELETED: 'PROJECT_MEMBER_DELETED',
    },
    PROJECT_TEAM: {
        ADDED: 'PROJECT_TEAM_ADDED',
        DELETED: 'PROJECT_TEAM_DELETED',
    },
    PROJECT_TEAM_MEMBER: {
        ADDED: 'PROJECT_TEAM_MEMBER_ADDED',
        DELETED: 'PROJECT_TEAM_MEMBER_DELETED',
    },
    PROJECT_TASK: {
        CREATED: 'PROJECT_TASK_CREATED',
        UPDATED: 'PROJECT_TASK_UPDATED',
        DELETED: 'PROJECT_TASK_DELETED',
        PARENT_DELETED: 'PROJECT_TASK_PARENT_DELETED',
        CHILDREN_DELETED: 'PROJECT_TASK_CHILDREN_DELETED',
    },
    PROJECT_TASK_TRIGGER: {
        TRIGGER: 'PROJECT_TASK_TRIGGER',
    },
} as const;

export const EVENT_TO_TOPIC: Record<string, string> = {
    [KAFKA_EVENTS.PROJECT.CREATED]: KAFKA_TOPICS.PROJECT,
    [KAFKA_EVENTS.PROJECT.DELETED]: KAFKA_TOPICS.PROJECT,
    [KAFKA_EVENTS.PROJECT_MEMBER.ADDED]: KAFKA_TOPICS.PROJECT_MEMBER,
    [KAFKA_EVENTS.PROJECT_MEMBER.DELETED]: KAFKA_TOPICS.PROJECT_MEMBER,
    [KAFKA_EVENTS.PROJECT_TEAM.ADDED]: KAFKA_TOPICS.PROJECT_TEAM,
    [KAFKA_EVENTS.PROJECT_TEAM.DELETED]: KAFKA_TOPICS.PROJECT_TEAM,
    [KAFKA_EVENTS.PROJECT_TEAM_MEMBER.ADDED]: KAFKA_TOPICS.PROJECT_TEAM_MEMBER,
    [KAFKA_EVENTS.PROJECT_TEAM_MEMBER.DELETED]:
        KAFKA_TOPICS.PROJECT_TEAM_MEMBER,
    [KAFKA_EVENTS.PROJECT_TASK.CREATED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.UPDATED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.PARENT_DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.CHILDREN_DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK_TRIGGER.TRIGGER]:
        KAFKA_TOPICS.PROJECT_TASK_TRIGGER,
};
