export const KAFKA_TOPICS = {
    PROJECT: 'project-events',
    PROJECT_MEMBER: 'project-member-events',
    PROJECT_TEAM: 'project-team-events',
    PROJECT_TEAM_MEMBER: 'project-team-member-events',
    PROJECT_TASK: 'project-task-events',
    PROJECT_TASK_TRIGGER: 'project-task-trigger-events',
    AUTH: 'auth-events',
    NOTIFICATION: 'notification-events',
} as const;

export const KAFKA_EVENTS = {
    PROJECT: { CREATED: 'PROJECT_CREATED', DELETED: 'PROJECT_DELETED' },
    PROJECT_MEMBER: {
        ADDED: 'PROJECT_MEMBER_ADDED',
        DELETED: 'PROJECT_MEMBER_DELETED',
    },
    PROJECT_TEAM: {
        ADDED: 'PROJECT_TEAM_ADDED',
        DELETED: 'PROJECT_TEAM_DELETED',
    },
    PROJECT_TEAM_MEMBER: {
        ADDED: 'PROJECT_TEAM_MEMBER_ADDED',
        DELETED: 'PROJECT_TEAM_MEMBER_DELETED',
    },
    PROJECT_TASK: {
        CREATED: 'PROJECT_TASK_CREATED',
        UPDATED: 'PROJECT_TASK_UPDATED',
        DELETED: 'PROJECT_TASK_DELETED',
        PARENT_DELETED: 'PROJECT_TASK_PARENT_DELETED',
        CHILDREN_DELETED: 'PROJECT_TASK_CHILDREN_DELETED',
    },
    PROJECT_TASK_TRIGGER: {
        TRIGGER: 'PROJECT_TASK_TRIGGER',
        DELETED: 'PROJECT_TASK_TRIGGER_DELETED',
    },
    AUTH: {
        SIGNUP_STARTED: 'AUTH_SIGNUP_STARTED',
        USER_CREATED: 'AUTH_USER_CREATED',
    },
    NOTIFICATION: {
        REQUESTED: 'NOTIFICATION_REQUESTED',
        CREATED: 'NOTIFICATION_CREATED',
    },
} as const;

export const EVENT_TO_TOPIC: Record<string, string> = {
    [KAFKA_EVENTS.PROJECT.CREATED]: KAFKA_TOPICS.PROJECT,
    [KAFKA_EVENTS.PROJECT.DELETED]: KAFKA_TOPICS.PROJECT,
    [KAFKA_EVENTS.PROJECT_MEMBER.ADDED]: KAFKA_TOPICS.PROJECT_MEMBER,
    [KAFKA_EVENTS.PROJECT_MEMBER.DELETED]: KAFKA_TOPICS.PROJECT_MEMBER,
    [KAFKA_EVENTS.PROJECT_TEAM.ADDED]: KAFKA_TOPICS.PROJECT_TEAM,
    [KAFKA_EVENTS.PROJECT_TEAM.DELETED]: KAFKA_TOPICS.PROJECT_TEAM,
    [KAFKA_EVENTS.PROJECT_TEAM_MEMBER.ADDED]: KAFKA_TOPICS.PROJECT_TEAM_MEMBER,
    [KAFKA_EVENTS.PROJECT_TEAM_MEMBER.DELETED]:
        KAFKA_TOPICS.PROJECT_TEAM_MEMBER,
    [KAFKA_EVENTS.PROJECT_TASK.CREATED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.UPDATED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.PARENT_DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK.CHILDREN_DELETED]: KAFKA_TOPICS.PROJECT_TASK,
    [KAFKA_EVENTS.PROJECT_TASK_TRIGGER.TRIGGER]:
        KAFKA_TOPICS.PROJECT_TASK_TRIGGER,
    [KAFKA_EVENTS.PROJECT_TASK_TRIGGER.DELETED]:
        KAFKA_TOPICS.PROJECT_TASK_TRIGGER,
    [KAFKA_EVENTS.AUTH.SIGNUP_STARTED]: KAFKA_TOPICS.AUTH,
    [KAFKA_EVENTS.AUTH.USER_CREATED]: KAFKA_TOPICS.AUTH,
    [KAFKA_EVENTS.NOTIFICATION.REQUESTED]: KAFKA_TOPICS.NOTIFICATION,
    [KAFKA_EVENTS.NOTIFICATION.CREATED]: KAFKA_TOPICS.NOTIFICATION,
};

/**
 * Maps the raw kafka_topic strings stored in outbox_events rows
 * back to the KAFKA_EVENTS type codes that Bus.publish() expects.
 * This allows the OutboxRelay to bridge between the DB and the MemoryBus.
 */
export const OUTBOX_TOPIC_TO_EVENT_TYPE: Record<string, string> = {
    'project.created': KAFKA_EVENTS.PROJECT.CREATED,
    'project.deleted': KAFKA_EVENTS.PROJECT.DELETED,
    'project.member.added': KAFKA_EVENTS.PROJECT_MEMBER.ADDED,
    'project.member.deleted': KAFKA_EVENTS.PROJECT_MEMBER.DELETED,
    'project.team.created': KAFKA_EVENTS.PROJECT_TEAM.ADDED,
    'project.team.deleted': KAFKA_EVENTS.PROJECT_TEAM.DELETED,
    'project.team.member.added': KAFKA_EVENTS.PROJECT_TEAM_MEMBER.ADDED,
    'project.team.member.deleted': KAFKA_EVENTS.PROJECT_TEAM_MEMBER.DELETED,
    'project.task.created': KAFKA_EVENTS.PROJECT_TASK.CREATED,
    'project.task.updated': KAFKA_EVENTS.PROJECT_TASK.UPDATED,
    'project.task.deleted': KAFKA_EVENTS.PROJECT_TASK.DELETED,
    'project.task.parent.deleted': KAFKA_EVENTS.PROJECT_TASK.PARENT_DELETED,
    'project.task.children.deleted': KAFKA_EVENTS.PROJECT_TASK.CHILDREN_DELETED,
    'project.task.trigger': KAFKA_EVENTS.PROJECT_TASK_TRIGGER.TRIGGER,
    'project.task.trigger.deleted': KAFKA_EVENTS.PROJECT_TASK_TRIGGER.DELETED,
    'auth.signup.started': KAFKA_EVENTS.AUTH.SIGNUP_STARTED,
    'auth.user.created': KAFKA_EVENTS.AUTH.USER_CREATED,
    'notification.requested': KAFKA_EVENTS.NOTIFICATION.REQUESTED,
};

