extend type Query {
    teams(projectId: ID!, memberId: ID, first: Int, after: String, last: Int, before: String): TeamConnection!
    teamMembers(
        projectId: ID!
        teamId: ID!
        first: Int
        after: String
        last: Int
        before: String
    ): TeamMemberConnection!
}

extend type Mutation {
    createTeam(projectId: ID!, name: String!): CreateTeamPayload
    deleteTeams(projectId: ID!, teamIds: [ID!]!): DeleteTeamsPayload
    addTeamMembers(
        projectId: ID!
        teamId: ID!
        userIds: [String!]!
    ): AddTeamMembersPayload
    removeTeamMembers(
        projectId: ID!
        teamId: ID!
        userIds: [String!]!
    ): RemoveTeamMembersPayload
}

type CreateTeamPayload {
    success: Boolean!
    team: Team
}

type DeleteTeamsPayload {
    success: Boolean!
    deletedCount: Int!
    project: Project
}

type AddTeamMembersPayload {
    success: Boolean!
    team: Team
}

type RemoveTeamMembersPayload {
    success: Boolean!
    team: Team
}
