"""
Template metadata for an Auto Action scope.
"""
type AutoActionTemplate {
    triggers: [AutoActionTriggerTemplate!]!
    contextFields: [String!]!
    actions: [AutoActionActionTemplate!]!
    conditions: [AutoActionConditionTemplate!]!
}

"""
Template for an individual trigger.
"""
type AutoActionTriggerTemplate {
    type: String!
    name: String!
    description: String!
    scope: String!
}

"""
Template for an individual action.
"""
type AutoActionActionTemplate {
    id: String!
    name: String!
    description: String!
    isSync: Boolean!
    scope: String!
    inputSchema: JSON!
}

"""
Template for an individual condition predicate.
"""
type AutoActionConditionTemplate {
    type: String!
    name: String!
    description: String
    isSync: Boolean!
    scope: String!
    schema: JSON!
}
