package dev.kuku.taskinator.domains.team.internal

import dev.kuku.taskinator.domains.team.*
import io.github.oshai.kotlinlogging.KotlinLogging
import org.springframework.stereotype.Component

private val log = KotlinLogging.logger {}

/**
 * TeamEventHandler is the background worker for the Team domain.
 * 
 * It manages the asynchronous lifecycle of teams, including hierarchy 
 * persistence and member management. By using the Unified Stream, 
 * it ensures that a team is only created AFTER its parent project exists.
 */
@Component
class TeamEventHandler(
    private val teamService: TeamService,
    private val teamRepo: TeamQueries
) {

    /**
     * Routes incoming TeamEvents to the correct persistence logic.
     */
    fun handle(event: TeamEvent) {
        when (event) {
            is TeamEvent.TeamCreated -> {
                log.info { "Processing TeamCreated: ${event.teamId}" }
                // ID-FIRST: Uses the teamId generated by the API to ensure 
                // the client has the correct reference immediately.
                teamRepo.insertTeam(event.projectId, event.userId, event.teamId, event.name, event.parentTeamId, event.idempotencyKey)
            }
            is TeamEvent.TeamRenamed -> {
                log.info { "Processing TeamRenamed: ${event.teamId}" }
                teamService.updateTeam(event.projectId, event.userId, event.teamId, UpdateTeamFields(
                    teamName = event.name,
                    version = event.version
                ))
            }
            is TeamEvent.TeamDeleted -> {
                log.info { "Processing TeamDeleted: ${event.teamId}" }
                teamService.deleteTeam(event.projectId, event.userId, event.teamId, event.version)
            }
            is TeamEvent.TeamMembersAdded -> {
                log.info { "Processing TeamMembersAdded: ${event.teamId}" }
                teamService.addTeamMembers(event.projectId, event.userId, event.teamId, event.memberIds)
            }
            is TeamEvent.TeamMembersRemoved -> {
                log.info { "Processing TeamMembersRemoved: ${event.teamId}" }
                teamService.removeTeamMembers(event.projectId, event.userId, event.teamId, event.memberIds)
            }
        }
    }
}
