package dev.kuku.taskinator.domains.team.internal

import com.github.f4b6a3.uuid.UuidCreator
import dev.kuku.taskinator.domains.project.internal.ProjectMembers
import dev.kuku.taskinator.domains.team.ProjectTeam
import dev.kuku.taskinator.domains.team.TeamNameConflictException
import dev.kuku.taskinator.domains.team.UpdateTeamFields
import org.jetbrains.exposed.v1.core.*
import org.jetbrains.exposed.v1.jdbc.deleteWhere
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.update
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Repository
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.util.*
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlin.uuid.toJavaUuid
import kotlin.uuid.toKotlinUuid

/**
 * TeamQueriesExposed handles high-performance Team and Hierarchy persistence.
 * 
 * DESIGN: Uses Closure Tables for O(1) ancestor/descendant lookups and 
 * CTEs for atomic, secured insertions.
 */
@Repository
class TeamQueriesExposed(private val jdbcTemplate: JdbcTemplate) : TeamQueries {

    private val MAX_DEPTH = 50

    /**
     * ATOMIC SECURE TEAM INSERTION
     * 
     * Handles:
     * 1. Authorization: User must be project owner or member.
     * 2. Hierarchy depth check: Prevents tree levels > 50.
     * 3. ID-First: Uses teamId generated by the API.
     * 4. Idempotency: Uses ON CONFLICT to ignore duplicate Kafka events.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun insertTeam(
        projectId: String,
        userId: String,
        teamId: String,
        teamName: String,
        parentTeamId: String?,
        idempotencyKey: String
    ): ProjectTeam? {
        val projectUuid = Uuid.parse(projectId)
        val userUuid = Uuid.parse(userId)
        val teamUuid = Uuid.parse(teamId)
        val parentUuid = parentTeamId?.let { Uuid.parse(it) }
        val now = LocalDateTime.now(ZoneOffset.UTC)
        val closureUuid = UuidCreator.getTimeOrderedEpoch().toKotlinUuid()

        val sql = """
            WITH inserted_team AS (
                INSERT INTO project_teams (id, fk_project_id, fk_parent_team_id, team_name, created_at, version, idempotency_key)
                SELECT ?::uuid, ?::uuid, ?::uuid, ?, ?, 0, ?
                WHERE (
                    EXISTS (SELECT 1 FROM projects WHERE id = ?::uuid AND fk_owner_id = ?::uuid)
                    OR EXISTS (SELECT 1 FROM project_members WHERE fk_project_id = ?::uuid AND fk_member_id = ?::uuid)
                )
                AND NOT EXISTS (
                    SELECT 1 FROM project_team_closure 
                    WHERE fk_child_id = ?::uuid AND fk_project_id = ?::uuid AND depth >= ? - 1
                )
                AND (?::uuid IS NULL OR EXISTS (SELECT 1 FROM project_team_closure WHERE fk_child_id = ?::uuid AND fk_project_id = ?::uuid))
                ON CONFLICT (idempotency_key) DO NOTHING
                RETURNING id, fk_project_id, created_at
            )
            INSERT INTO project_team_closure (id, fk_project_id, fk_team_id, fk_child_id, depth, created_at)
            SELECT ?::uuid, fk_project_id, id, id, 0, created_at
            FROM inserted_team
        """.trimIndent()

        try {
            val rowsAffected = jdbcTemplate.update(
                sql,
                teamUuid.toJavaUuid(),
                projectUuid.toJavaUuid(),
                parentUuid?.toJavaUuid(),
                teamName,
                now,
                idempotencyKey,
                projectUuid.toJavaUuid(),
                userUuid.toJavaUuid(),
                projectUuid.toJavaUuid(),
                userUuid.toJavaUuid(),
                parentUuid?.toJavaUuid(),
                projectUuid.toJavaUuid(),
                MAX_DEPTH,
                parentUuid?.toJavaUuid(),
                parentUuid?.toJavaUuid(),
                projectUuid.toJavaUuid(),
                closureUuid.toJavaUuid()
            )

            if (rowsAffected == 0) {
                // FALLBACK for Idempotency: If key exists, return existing team
                val existingTeam = ProjectTeams.selectAll()
                    .where { (ProjectTeams.idempotencyKey eq idempotencyKey) or (ProjectTeams.id eq teamUuid) }
                    .singleOrNull()
                
                if (existingTeam != null) {
                    return existingTeam.toProjectTeam()
                }

                // Diagnostics for failures other than idempotency
                val ownerId = findProjectOwner(projectId)
                val isMember = filterProjectMembers(projectId, listOf(userId)).isNotEmpty()

                if (ownerId == null) throw IllegalArgumentException("Project not found.")
                if (ownerId != userId && !isMember) throw IllegalArgumentException("Unauthorized: User is not a member of the project.")

                if (parentUuid != null) {
                    val parentDepth = ProjectTeamClosure
                        .selectAll()
                        .where { (ProjectTeamClosure.childId eq parentUuid) and (ProjectTeamClosure.projectId eq projectUuid) }
                        .orderBy(ProjectTeamClosure.depth to SortOrder.DESC, ProjectTeamClosure.id to SortOrder.ASC)
                        .limit(1)
                        .map { it[ProjectTeamClosure.depth] }
                        .singleOrNull()
                        ?: throw IllegalArgumentException("Parent team '$parentTeamId' not found in this project.")

                    if (parentDepth >= MAX_DEPTH - 1) {
                        throw IllegalArgumentException("Maximum team hierarchy depth reached ($MAX_DEPTH).")
                    }
                }
                return null
            }
        } catch (e: Exception) {
            if (e.message?.contains("Unique", ignoreCase = true) == true ||
                e.message?.contains("duplicate", ignoreCase = true) == true
            ) {
                throw TeamNameConflictException("Team with name '$teamName' already exists in this project.")
            }
            throw e
        }

        return ProjectTeam(
            id = teamUuid.toString(),
            name = teamName,
            projectId = projectId,
            parentTeamId = parentTeamId,
            createdAt = Date.from(now.toInstant(ZoneOffset.UTC)),
            updatedAt = Date.from(now.toInstant(ZoneOffset.UTC))
        )
    }

    /**
     * ATOMIC HIERARCHY COPY
     * Inherits all ancestral paths from parent to child in a single bulk INSERT.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun computeTeamHierarchy(projectId: String, teamId: String, parentTeamId: String) {
        val projectUuid = Uuid.parse(projectId)
        val teamUuid = Uuid.parse(teamId)
        val parentUuid = Uuid.parse(parentTeamId)
        val now = LocalDateTime.now(ZoneOffset.UTC)

        val sql = """
            INSERT INTO project_team_closure (id, fk_project_id, fk_team_id, fk_child_id, depth, created_at)
            SELECT gen_random_uuid(), fk_project_id, fk_team_id, ?, depth + 1, ?
            FROM project_team_closure
            WHERE fk_child_id = ? AND fk_project_id = ?
            ON CONFLICT DO NOTHING
        """.trimIndent()

        jdbcTemplate.update(
            sql,
            teamUuid.toJavaUuid(),
            now,
            parentUuid.toJavaUuid(),
            projectUuid.toJavaUuid()
        )
    }


    @OptIn(ExperimentalUuidApi::class)
    override fun updateTeam(
        projectId: String,
        teamId: String,
        toUpdate: UpdateTeamFields
    ): Boolean {
        val teamUuid = Uuid.parse(teamId)
        val projectUuid = Uuid.parse(projectId)
        val now = LocalDateTime.now(ZoneOffset.UTC)

        try {
            val rowsAffected = if (toUpdate.parentTeamId != null) {
                val newParentUuid = Uuid.parse(toUpdate.parentTeamId)

                val sql = """
                    UPDATE project_teams 
                    SET fk_parent_team_id = ?, 
                        team_name = COALESCE(?, team_name), 
                        version = version + 1, 
                        updated_at = ?
                    WHERE id = ? AND fk_project_id = ? AND version = ?
                    AND EXISTS (
                        SELECT 1 FROM project_team_closure 
                        WHERE fk_child_id = ?::uuid AND fk_project_id = ?::uuid AND depth < ? - 1
                    )
                    AND NOT EXISTS (
                        SELECT 1 FROM project_team_closure 
                        WHERE fk_team_id = ? AND fk_child_id = ? AND fk_project_id = ?
                    )
                """.trimIndent()

                jdbcTemplate.update(
                    sql,
                    newParentUuid.toJavaUuid(),
                    toUpdate.teamName,
                    now,
                    teamUuid.toJavaUuid(),
                    projectUuid.toJavaUuid(),
                    toUpdate.version,
                    newParentUuid.toJavaUuid(),
                    projectUuid.toJavaUuid(),
                    MAX_DEPTH,
                    teamUuid.toJavaUuid(),
                    newParentUuid.toJavaUuid(),
                    projectUuid.toJavaUuid()
                )
            } else {
                ProjectTeams.update({
                    (ProjectTeams.id eq teamUuid) and
                            (ProjectTeams.projectId eq projectUuid) and
                            (ProjectTeams.version eq toUpdate.version)
                }) {
                    if (toUpdate.teamName != null) it[teamName] = toUpdate.teamName
                    it[version] = toUpdate.version + 1
                    it[updatedAt] = now
                }
            }

            if (rowsAffected == 0) {
                if (toUpdate.parentTeamId != null) {
                    val newParentUuid = Uuid.parse(toUpdate.parentTeamId)
                    val exists = ProjectTeams.selectAll()
                        .where { (ProjectTeams.id eq teamUuid) and (ProjectTeams.projectId eq projectUuid) and (ProjectTeams.version eq toUpdate.version) }
                        .any()
                    if (!exists) return false 

                    val parentDepth = ProjectTeamClosure
                        .selectAll()
                        .where { (ProjectTeamClosure.childId eq newParentUuid) and (ProjectTeamClosure.projectId eq projectUuid) }
                        .orderBy(ProjectTeamClosure.depth to SortOrder.DESC, ProjectTeamClosure.id to SortOrder.ASC)
                        .limit(1)
                        .map { it[ProjectTeamClosure.depth] }
                        .singleOrNull()
                        ?: throw IllegalArgumentException("Parent team '${toUpdate.parentTeamId}' not found.")

                    if (parentDepth >= MAX_DEPTH - 1) {
                        throw IllegalArgumentException("Maximum team hierarchy depth reached ($MAX_DEPTH).")
                    }

                    val isDescendant = ProjectTeamClosure.selectAll()
                        .where { (ProjectTeamClosure.teamId eq teamUuid) and (ProjectTeamClosure.childId eq newParentUuid) and (ProjectTeamClosure.projectId eq projectUuid) }
                        .any()
                    if (isDescendant) {
                        throw IllegalArgumentException("Cycle detected: Cannot move team under its own descendant.")
                    }
                }
                return false
            }
            return true
        } catch (e: Exception) {
            if (e.message?.contains("Unique", ignoreCase = true) == true ||
                e.message?.contains("duplicate", ignoreCase = true) == true
            ) {
                throw TeamNameConflictException("Team with name '${toUpdate.teamName}' already exists.")
            }
            throw e
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteTeam(projectId: String, teamId: String, version: Long): Int {
        val teamUuid = Uuid.parse(teamId)
        val projectUuid = Uuid.parse(projectId)

        val sql = """
            WITH deleted_team AS (
                DELETE FROM project_teams 
                WHERE id = ? AND fk_project_id = ? AND version = ?
                RETURNING id
            ),
            deleted_closure AS (
                DELETE FROM project_team_closure 
                WHERE (fk_team_id IN (SELECT id FROM deleted_team) OR fk_child_id IN (SELECT id FROM deleted_team))
            )
            SELECT COUNT(*) FROM deleted_team
        """.trimIndent()

        return jdbcTemplate.queryForObject(
            sql,
            Int::class.java,
            teamUuid.toJavaUuid(),
            projectUuid.toJavaUuid(),
            version
        ) ?: 0
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findTeamsByProject(projectId: String, limit: Int, offset: Int): List<ProjectTeam> {
        val projectUuid = Uuid.parse(projectId)

        return ProjectTeams.selectAll()
            .where { ProjectTeams.projectId eq projectUuid }
            .orderBy(ProjectTeams.createdAt to SortOrder.DESC, ProjectTeams.id to SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map { it.toProjectTeam() }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun filterProjectMembers(projectId: String, memberIds: List<String>): List<String> {
        val projectUuid = Uuid.parse(projectId)
        val memberUuids = memberIds.map { Uuid.parse(it) }

        return ProjectMembers.selectAll()
            .where { (ProjectMembers.projectId eq projectUuid) and (ProjectMembers.memberId inList memberUuids) }
            .map { it[ProjectMembers.memberId].toString() }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findTeamById(projectId: String, teamId: String): ProjectTeam? {
        val projectUuid = Uuid.parse(projectId)
        val teamUuid = Uuid.parse(teamId)

        return ProjectTeams.selectAll()
            .where { (ProjectTeams.projectId eq projectUuid) and (ProjectTeams.id eq teamUuid) }
            .map { it.toProjectTeam() }
            .singleOrNull()
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findProjectOwner(projectId: String): String? {
        val projectUuid = Uuid.parse(projectId)
        return dev.kuku.taskinator.domains.project.internal.Projects.selectAll()
            .where { dev.kuku.taskinator.domains.project.internal.Projects.id eq projectUuid }
            .map { it[dev.kuku.taskinator.domains.project.internal.Projects.ownerId].toString() }
            .singleOrNull()
    }

    override fun getChildrenTeam(
        projectId: String,
        userId: String,
        teamId: String,
        limit: Int,
        offset: Int
    ): List<ProjectTeam> {
        throw NotImplementedError("WIP")
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun insertTeamMembers(
        projectId: String,
        teamId: String,
        memberIds: List<String>
    ) {
        val projectUuid = Uuid.parse(projectId)
        val teamUuid = Uuid.parse(teamId)
        val memberUuids = memberIds.map { Uuid.parse(it).toJavaUuid() }.toTypedArray()
        val now = LocalDateTime.now(ZoneOffset.UTC)

        val sql = """
            INSERT INTO project_team_members (id, fk_project_id, fk_team_id, fk_member_id, username, display_name, created_at)
            SELECT gen_random_uuid(), fk_project_id, ?, fk_member_id, username, display_name, ?
            FROM (
                SELECT fk_project_id, fk_member_id, username, display_name 
                FROM project_members 
                WHERE fk_project_id = ? AND fk_member_id = ANY(?)
                UNION ALL
                SELECT id, fk_owner_id, 'owner', 'Project Owner'
                FROM projects
                WHERE id = ? AND fk_owner_id = ANY(?)
            ) sub
            ON CONFLICT (fk_project_id, fk_team_id, fk_member_id) DO NOTHING
        """.trimIndent()

        jdbcTemplate.update(sql) { ps ->
            ps.setObject(1, teamUuid.toJavaUuid())
            ps.setTimestamp(2, java.sql.Timestamp.valueOf(now))
            ps.setObject(3, projectUuid.toJavaUuid())
            ps.setArray(4, ps.connection.createArrayOf("uuid", memberUuids))
            ps.setObject(5, projectUuid.toJavaUuid())
            ps.setArray(6, ps.connection.createArrayOf("uuid", memberUuids))
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteTeamMembers(
        projectId: String,
        teamId: String,
        memberIds: List<String>
    ) {
        val teamUuid = Uuid.parse(teamId)
        val projectUuid = Uuid.parse(projectId)
        val memberUuids = memberIds.map { Uuid.parse(it) }

        ProjectTeamMembers.deleteWhere {
            (ProjectTeamMembers.projectId eq projectUuid) and
                    (ProjectTeamMembers.teamId eq teamUuid) and
                    (ProjectTeamMembers.memberId inList memberUuids)
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    private fun ResultRow.toProjectTeam() = ProjectTeam(
        id = this[ProjectTeams.id].value.toString(),
        name = this[ProjectTeams.teamName],
        projectId = this[ProjectTeams.projectId].toString(),
        parentTeamId = this[ProjectTeams.parentTeamId]?.toString(),
        createdAt = Date.from(this[ProjectTeams.createdAt].toInstant(ZoneOffset.UTC)),
        updatedAt = this[ProjectTeams.updatedAt]?.let { Date.from(it.toInstant(ZoneOffset.UTC)) }
    )

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteTeamsByProjectBatch(projectId: String, limit: Int): Int {
        val projectUuid = Uuid.parse(projectId).toJavaUuid()

        val sql = """
            WITH target_teams AS (
                SELECT id FROM project_teams 
                WHERE fk_project_id = ?::uuid 
                LIMIT ?
            ),
            deleted_members AS (
                DELETE FROM project_team_members 
                WHERE fk_team_id IN (SELECT id FROM target_teams)
            ),
            deleted_closure AS (
                DELETE FROM project_team_closure 
                WHERE fk_team_id IN (SELECT id FROM target_teams) 
                OR fk_child_id IN (SELECT id FROM target_teams)
            )
            DELETE FROM project_teams 
            WHERE id IN (SELECT id FROM target_teams)
        """.trimIndent()

        return jdbcTemplate.update(sql, projectUuid, limit)
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun getDescendantTeamIds(projectId: String, teamId: String): List<String> {
        val projectUuid = Uuid.parse(projectId)
        val teamUuid = Uuid.parse(teamId)
        
        return ProjectTeamClosure.selectAll()
            .where { (ProjectTeamClosure.projectId eq projectUuid) and (ProjectTeamClosure.teamId eq teamUuid) and (ProjectTeamClosure.childId neq teamUuid) }
            .map { it[ProjectTeamClosure.childId].toString() }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteSpecificTeamsBatch(projectId: String, teamIds: List<String>, limit: Int): Int {
        if (teamIds.isEmpty()) return 0
        val projectUuid = Uuid.parse(projectId).toJavaUuid()
        val teamUuids = teamIds.map { Uuid.parse(it).toJavaUuid() }.toTypedArray()

        val sql = """
            WITH target_teams AS (
                SELECT id FROM project_teams 
                WHERE fk_project_id = ?::uuid AND id = ANY(?) 
                LIMIT ?
            ),
            deleted_members AS (
                DELETE FROM project_team_members 
                WHERE fk_team_id IN (SELECT id FROM target_teams)
            ),
            deleted_closure AS (
                DELETE FROM project_team_closure 
                WHERE fk_team_id IN (SELECT id FROM target_teams) 
                OR fk_child_id IN (SELECT id FROM target_teams)
            )
            DELETE FROM project_teams 
            WHERE id IN (SELECT id FROM target_teams)
        """.trimIndent()

        return jdbcTemplate.update(sql) { ps ->
            ps.setObject(1, projectUuid)
            ps.setArray(2, ps.connection.createArrayOf("uuid", teamUuids))
            ps.setInt(3, limit)
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteTeamMembersForMembersBatch(projectId: String, memberIds: List<String>, limit: Int): Int {
        if (memberIds.isEmpty()) return 0
        val projectUuid = Uuid.parse(projectId).toJavaUuid()
        val memberUuids = memberIds.map { Uuid.parse(it).toJavaUuid() }.toTypedArray()

        val sql = """
            DELETE FROM project_team_members 
            WHERE id IN (
                SELECT id FROM project_team_members 
                WHERE fk_project_id = ?::uuid AND fk_member_id = ANY(?) 
                LIMIT ?
            )
        """.trimIndent()

        return jdbcTemplate.update(sql) { ps ->
            ps.setObject(1, projectUuid)
            ps.setArray(2, ps.connection.createArrayOf("uuid", memberUuids))
            ps.setInt(3, limit)
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findTeamMembers(projectId: String, teamId: String, limit: Int, offset: Int): List<dev.kuku.taskinator.domains.team.ProjectTeamMember> {
        val projectUuid = Uuid.parse(projectId)
        val teamUuid = Uuid.parse(teamId)
        return ProjectTeamMembers.selectAll()
            .where { (ProjectTeamMembers.projectId eq projectUuid) and (ProjectTeamMembers.teamId eq teamUuid) }
            .orderBy(ProjectTeamMembers.createdAt to SortOrder.DESC, ProjectTeamMembers.id to SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map {
                dev.kuku.taskinator.domains.team.ProjectTeamMember(
                    id = it[ProjectTeamMembers.id].value.toString(),
                    memberId = it[ProjectTeamMembers.memberId].toString(),
                    teamId = it[ProjectTeamMembers.teamId].toString(),
                    createdAt = Date.from(it[ProjectTeamMembers.createdAt].toInstant(ZoneOffset.UTC)),
                    updatedAt = it[ProjectTeamMembers.updatedAt]?.let { d -> Date.from(d.toInstant(ZoneOffset.UTC)) }
                )
            }
    }
}
