export const enum ProjectEvent {
    PROJECT_CREATED = "PROJECT_CREATED",
    PROJECT_DELETED = "PROJECT_DELETED",
    PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED",
    PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED",

}