package dev.kuku.taskinator.domains.project.internal

import dev.kuku.taskinator.domains.project.*
import io.github.oshai.kotlinlogging.KotlinLogging
import org.springframework.stereotype.Component

private val log = KotlinLogging.logger {}

/**
 * ProjectEventHandler is the background worker for the Project domain.
 * 
 * It receives events from the Unified Workspace Stream and performs the 
 * final database persistence. This decoupling ensures the API stays 
 * responsive (<10ms) even during heavy DB load.
 */
@Component
class ProjectEventHandler(
    private val projectService: ProjectService,
    private val projectRepo: ProjectQueries
) {

    /**
     * Routes the incoming ProjectEvent to the appropriate repository method.
     * 
     * NOTE: We call projectRepo directly for 'Created' events to preserve 
     * the 'idempotencyKey' which is not exposed in the public ProjectService.
     */
    fun handle(event: ProjectEvent) {
        when (event) {
            is ProjectEvent.ProjectCreated -> {
                log.info { "Processing ProjectCreated: ${event.projectId}" }
                // ID-FIRST: We pass the event.projectId which was generated by the API.
                projectRepo.insertProject(event.projectId, event.name, event.userId, event.description, event.idempotencyKey)
            }
            is ProjectEvent.ProjectRenamed -> {
                log.info { "Processing ProjectRenamed: ${event.projectId}" }
                projectService.renameProject(event.userId, event.projectId, ProjectFieldsToUpdate(
                    name = event.name,
                    description = event.description,
                    version = event.version
                ))
            }
            is ProjectEvent.ProjectDeleted -> {
                log.info { "Processing ProjectDeleted: ${event.projectId}" }
                projectService.deleteProject(event.projectId, event.userId, event.version)
            }
            is ProjectEvent.ProjectMembersAdded -> {
                log.info { "Processing ProjectMembersAdded: ${event.projectId}" }
                projectService.addProjectMembers(event.projectId, event.userId, event.memberIds)
            }
            is ProjectEvent.ProjectMembersRemoved -> {
                log.info { "Processing ProjectMembersRemoved: ${event.projectId}" }
                projectService.removeProjectMembers(event.projectId, event.userId, event.memberIds)
            }
        }
    }
}
