package dev.kuku.taskinator.domains.project.internal

import dev.kuku.taskinator.domains.project.*
import io.github.oshai.kotlinlogging.KotlinLogging
import org.jetbrains.exposed.v1.core.*
import org.jetbrains.exposed.v1.jdbc.*
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Repository
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.util.*
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlin.uuid.toJavaUuid

private val log = KotlinLogging.logger {}

/**
 * ProjectQueriesExposed handles high-performance Project persistence.
 * 
 * Optimized for high-frequency operations by using raw SQL for 
 * 'One Round Trip' atomic insertions and idempotency protection.
 */
@Repository
class ProjectQueriesExposed(private val jdbcTemplate: JdbcTemplate) : ProjectQueries {

    /**
     * ATOMIC INSERT WITH IDEMPOTENCY
     * 
     * This method supports the 'ID-First' architecture by accepting a projectId 
     * generated by the API.
     * 
     * IDEMPOTENCY: Uses 'ON CONFLICT (idempotency_key) DO NOTHING' to ensure
     * that even if Kafka delivers this creation event twice, only one project 
     * will ever be saved.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun insertProject(
        projectId: String,
        name: String,
        ownerId: String,
        description: String?,
        idempotencyKey: String
    ): ProjectInfo? {
        log.debug { "Insert project $name for owner $ownerId with ID $projectId" }

        val now = LocalDateTime.now(ZoneOffset.UTC)
        
        val sql = """
            INSERT INTO projects (
                id, project_name, fk_owner_id, description, created_at, version, idempotency_key
            )
            VALUES (?::uuid, ?, ?, ?, ?, 0, ?)
            ON CONFLICT (idempotency_key) DO NOTHING
            RETURNING *
        """.trimIndent()

        val result = jdbcTemplate.query(sql, { rs, _ ->
            ProjectInfo(
                id = rs.getString("id"),
                name = rs.getString("project_name"),
                owner = rs.getString("fk_owner_id"),
                description = rs.getString("description"),
                createdAt = rs.getTimestamp("created_at"),
                updatedAt = rs.getTimestamp("updated_at")
            )
        }, 
            Uuid.parse(projectId).toJavaUuid(),
            name,
            Uuid.parse(ownerId).toJavaUuid(),
            description ?: "",
            now,
            idempotencyKey
        )

        /**
         * FALLBACK: If the INSERT returned null (due to idempotency conflict), 
         * we fetch and return the existing record to satisfy the caller.
         */
        return result.firstOrNull() ?: findProjectById(projectId, ownerId)
    }

    /**
     * OPTIMISTIC PROJECT UPDATE:
     * Enforces strict version matching to prevent 'Lost Update' anomalies
     * during high-concurrency renames.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun updateProject(
        projectId: String,
        userId: String,
        toUpdate: ProjectFieldsToUpdate
    ) {
        log.debug { "Updating project $projectId for user $userId" }

        try {
            val updatedRows = Projects.update({
                (Projects.id eq Uuid.parse(projectId)) and
                        (Projects.ownerId eq Uuid.parse(userId)) and
                        (Projects.version eq toUpdate.version)
            }) {
                if (toUpdate.name != null) it[Projects.projectName] = toUpdate.name
                if (toUpdate.description != null) it[Projects.description] = toUpdate.description

                it[Projects.version] = toUpdate.version + 1
                it[Projects.updatedAt] = LocalDateTime.now(ZoneOffset.UTC)
            }

            if (updatedRows == 0) {
                throw ProjectConcurrencyException("Update failed: Concurrency conflict.")
            }
        } catch (e: Exception) {
            if (e is ProjectConcurrencyException) throw e
            if (e.message?.contains("Unique", ignoreCase = true) == true || 
                e.message?.contains("duplicate", ignoreCase = true) == true) {
                throw ProjectNameConflictException("Project name conflict.")
            }
            throw e
        }
    }

    /**
     * SECURE BATCH MEMBER INSERTION:
     * Cross-joins the target project with a list of member IDs, ensuring 
     * that members are only added if the project owner is the requester.
     */
    @OptIn(ExperimentalUuidApi::class)
    override fun insertProjectMembers(
        projectId: String,
        userId: String,
        memberIds: List<String>
    ) {
        val projectUuid = Uuid.parse(projectId)
        val ownerUuid = Uuid.parse(userId)
        val memberUuids = memberIds.map { Uuid.parse(it).toJavaUuid() }.toTypedArray()
        val now = LocalDateTime.now(ZoneOffset.UTC)

        val sql = """
            INSERT INTO project_members (id, fk_project_id, fk_owner_id, fk_member_id, username, display_name, created_at)
            SELECT gen_random_uuid(), p.id, p.fk_owner_id, m.id, 'member_' || m.id, 'Member ' || m.id, ?
            FROM projects p
            CROSS JOIN (SELECT unnest(?) as id) m
            WHERE p.id = ? AND p.fk_owner_id = ?
            ON CONFLICT (fk_project_id, fk_member_id) DO NOTHING
        """.trimIndent()

        val rows = jdbcTemplate.update(sql) { ps ->
            ps.setTimestamp(1, java.sql.Timestamp.valueOf(now))
            ps.setArray(2, ps.connection.createArrayOf("uuid", memberUuids))
            ps.setObject(3, projectUuid.toJavaUuid())
            ps.setObject(4, ownerUuid.toJavaUuid())
        }

        if (rows == 0 && memberIds.isNotEmpty()) {
            val exists = Projects.selectAll()
                .where { (Projects.id eq projectUuid) and (Projects.ownerId eq ownerUuid) }
                .any()
            if (!exists) {
                throw IllegalArgumentException("Project not found or unauthorized.")
            }
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteProject(projectId: String, userId: String, version: Long): Int {
        val projectUuid = Uuid.parse(projectId)
        val ownerUuid = Uuid.parse(userId)

        val refinedSql = """
            WITH deleted_project AS (
                DELETE FROM projects 
                WHERE id = ? AND fk_owner_id = ? AND version = ?
                RETURNING id
            ),
            deleted_members AS (
                DELETE FROM project_members 
                WHERE fk_project_id IN (SELECT id FROM deleted_project)
            )
            SELECT COUNT(*) FROM deleted_project
        """.trimIndent()

        return jdbcTemplate.queryForObject(
            refinedSql,
            Int::class.java,
            projectUuid.toJavaUuid(),
            ownerUuid.toJavaUuid(),
            version
        ) ?: 0
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findProjectIdsByUserMembership(userId: String, limit: Int, offset: Int): List<String> {
        return ProjectMembers.selectAll()
            .where { ProjectMembers.memberId eq Uuid.parse(userId) }
            .orderBy(ProjectMembers.createdAt to SortOrder.DESC, ProjectMembers.id to SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map { it[ProjectMembers.projectId].toString() }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findProjectMembers(
        projectId: String,
        userId: String,
        sortBy: ProjectMemberSortKey,
        offset: Int,
        limit: Int
    ): List<ProjectMember> {
        val sortColumn = when (sortBy) {
            ProjectMemberSortKey.ADDED -> ProjectMembers.createdAt
            ProjectMemberSortKey.NAME -> ProjectMembers.displayName
        }

        return ProjectMembers.selectAll()
            .where {
                (ProjectMembers.projectId eq Uuid.parse(projectId)) and (ProjectMembers.ownerId eq Uuid.parse(userId))
            }
            .orderBy(sortColumn to SortOrder.ASC, ProjectMembers.id to SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map { it.toProjectMember() }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteProjectMembers(projectId: String, userId: String, memberIds: List<String>) {
        ProjectMembers.deleteWhere {
            (ProjectMembers.projectId eq Uuid.parse(projectId)) and
                    (ProjectMembers.ownerId eq Uuid.parse(userId)) and
                    (ProjectMembers.memberId inList memberIds.map { Uuid.parse(it) })
        }
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findProjectById(projectId: String, userId: String): ProjectInfo? {
        return Projects.selectAll()
            .where { (Projects.id eq Uuid.parse(projectId)) and (Projects.ownerId eq Uuid.parse(userId)) }
            .map { it.toProjectInfo() }
            .singleOrNull()
    }

    @OptIn(ExperimentalUuidApi::class)
    override fun findProjectsByOwner(userId: String, limit: Int, offset: Int): List<ProjectInfo> {
        return Projects.selectAll()
            .where { Projects.ownerId eq Uuid.parse(userId) }
            .orderBy(Projects.createdAt to SortOrder.DESC, Projects.id to SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map { it.toProjectInfo() }
    }

    @OptIn(ExperimentalUuidApi::class)
    private fun ResultRow.toProjectMember() = ProjectMember(
        projectId = this[ProjectMembers.projectId].toString(),
        memberId = this[ProjectMembers.memberId].toString(),
        createdAt = Date.from(this[ProjectMembers.createdAt].toInstant(ZoneOffset.UTC))
    )

    @OptIn(ExperimentalUuidApi::class)
    private fun ResultRow.toProjectInfo() = ProjectInfo(
        id = this[Projects.id].value.toString(),
        name = this[Projects.projectName],
        owner = this[Projects.ownerId].toString(),
        description = this[Projects.description],
        createdAt = Date.from(this[Projects.createdAt].toInstant(ZoneOffset.UTC)),
        updatedAt = this[Projects.updatedAt]?.let {
            Date.from(it.toInstant(ZoneOffset.UTC))
        }
    )

    @OptIn(ExperimentalUuidApi::class)
    override fun deleteProjectMembersByProject(projectId: String): Int {
        val projectUuid = Uuid.parse(projectId).toJavaUuid()
        val sql = "DELETE FROM project_members WHERE fk_project_id = ?"
        return jdbcTemplate.update(sql, projectUuid)
    }
}
