extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0",
        import: ["@key", "@shareable"])

type User @key(fields: "id") {
  id: ID!
  username: String! @shareable
  displayName: String! @shareable
  email: String! @shareable
  createdAt: String!
  updatedAt: String
}

type AuthResponse {
  success: Boolean!
  message: String!
  token: String
}

type Query {
  me: User
  userById(id: ID!): User
}

type Mutation {
  signUp(input: SignUpInput!): AuthResponse!
  completeSignUp(token: String!): AuthResponse!
  signIn(input: SignInInput!): AuthResponse!
  resetPassword(email: String!, password: String!): AuthResponse!
  completeResetPassword(token: String!): AuthResponse!
  updatePassword(input: UpdatePasswordInput!): AuthResponse!
}

input SignUpInput {
  email: String!
  password: String!
  username: String!
  displayName: String!
}

input SignInInput {
  key: String!
  method: SignInMethod!
  password: String!
}

enum SignInMethod {
  EMAIL
  USER
}

input UpdatePasswordInput {
  email: String!
  currentPassword: String!
  newPassword: String!
}
