spring:
  application:
    name: workspace
  datasource:
    url: jdbc:postgresql://localhost:5432/workspace?reWriteBatchedInserts=true
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
