spring:
  application:
    name: workspace
  datasource:
    url: jdbc:postgresql://localhost:5432/workspace?reWriteBatchedInserts=true
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

dgs:
  graphql:
    schema-locations:
      - classpath:graphql/**/*.graphql*
