# Federation 2.0 Directives
extend schema
@link(url: "https://specs.apollo.dev/federation/v2.0",
  import: ["@key", "@shareable", "@external"])

type Query {
  project(id: ID!): Project
  team(id: ID!): Team
}

# REUSABLE INPUTS
input PaginationInput {
  limit: Int = 10
  offset: Int = 0
}

# --- EXTENSIONS ---
type User @key(fields: "id") {
  id: ID! @external
  projects(pagination: PaginationInput): [Project!]!
}

# --- CORE TYPES ---
type Project @key(fields: "id") {
  id: ID!
  name: String! @shareable
  owner: User!
  description: String
  createdAt: String!
  updatedAt: String
  teams(pagination: PaginationInput): [Team!]!
  members(pagination: PaginationInput): [ProjectMember!]!
}

type ProjectMember {
  user: User!
  createdAt: String!
}

type Team @key(fields: "id") {
  id: ID!
  name: String!
  projectId: ID!
  parentTeamId: ID
  createdAt: String!
  members(pagination: PaginationInput): [TeamMember!]!
}

type TeamMember {
  user: User!
  createdAt: String!
}
