# Federation 2.0 Directives
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0",
        import: ["@key", "@shareable", "@external"])

type GenericResponse{
    success: Boolean!
    message: String
}


type Query {
    project(input: ProjectInput!): Project
    team(input: TeamInput!): Team
}

type Mutation {
    project: ProjectMutation!
    team: TeamMutation!
    task: TaskMutation!
}

type ProjectMutation{
    createProject(input: CreateProjectInput!): CreateProjectResponse!
    renameProject(input: RenameProjectInput!): GenericResponse!
    deleteProject(input: DeleteProjectInput!): GenericResponse!
    addProjectMembers(input: AddProjectMembersInput!): GenericResponse!
    removeProjectMembers(input: RemoveProjectMembersInput!): GenericResponse!
}

type CreateProjectResponse {
    success: Boolean!
    message: String
    response: Project
}


type TeamMutation{
    createTeam(input: CreateTeamInput!): CreateTeamResponse!
    updateTeam(input: UpdateTeamInput!): GenericResponse!
    deleteTeam(input: DeleteTeamInput!): GenericResponse!
    addTeamMembers(input: AddTeamMembersInput!): GenericResponse!
    removeTeamMembers(input: RemoveTeamMembersInput!): GenericResponse!
}

type CreateTeamResponse {
    success: Boolean!
    message: String
    response: Team
}

type TaskMutation {
    createTask(input: CreateTaskInput!): CreateTaskResponse!
    assignTask(input: AssignTaskInput!): GenericResponse!
    updateTaskStatus(input: UpdateTaskStatusInput!): GenericResponse!
    deleteTask(input: DeleteTaskInput!): GenericResponse!
}

type CreateTaskResponse {
    success: Boolean!
    message: String
    response: Task
}

# INPUT OBJECTS
input ProjectInput {
    id: ID!
}

input CreateProjectInput{
    name: String!
    description: String
}

input RenameProjectInput {
    projectId: ID!
    version: Int!
    name: String
    description: String
}

input DeleteProjectInput {
    projectId: ID!
    version: Int!
}

input AddProjectMembersInput{
    projectId: ID!
    memberIds: [ID!]!
}

input RemoveProjectMembersInput{
    projectId: ID!
    memberIds: [ID!]!
}

input TeamInput {
    id: ID!
}

input CreateTeamInput{
    projectId: ID!
    name: String!
    parentTeamId: ID
}

input UpdateTeamInput{
    projectId: ID!
    teamId: ID!
    version: Int!
    name: String
    parentTeamId: ID
}

input DeleteTeamInput {
    projectId: ID!
    teamId: ID!
    version: Int!
}

input AddTeamMembersInput{
    projectId: ID!
    teamId: ID!
    memberIds: [ID!]!
}

input RemoveTeamMembersInput{
    projectId: ID!
    teamId: ID!
    memberIds: [ID!]!
}

input CreateTaskInput {
    projectId: ID!
    title: String!
    description: String
    parentTaskId: ID
    assignedTeamId: ID
    assignedMemberId: ID
}

input AssignTaskInput {
    projectId: ID!
    taskId: ID!
    version: Int!
    teamId: ID
    teamMemberId: ID
}

input UpdateTaskStatusInput {
    projectId: ID!
    taskId: ID!
    version: Int!
    status: String!
}

input DeleteTaskInput {
    projectId: ID!
    taskId: ID!
    version: Int!
}

input PaginationInput {
    limit: Int = 10
    offset: Int = 0
}

# --- EXTENSIONS ---
type User @key(fields: "id") {
    id: ID! @shareable
    projects(input: PaginationInput): [Project!]!
}

# --- CORE TYPES ---
type Project @key(fields: "id") {
    id: ID!
    name: String! @shareable
    owner: User! 
    description: String
    createdAt: String!
    updatedAt: String
    teams(input: PaginationInput): [Team!]!
    members(input: PaginationInput): [ProjectMember!]!
    tasks(input: PaginationInput): [Task!]!
}

type ProjectMember {
    user: User!
    createdAt: String!
}

type Team @key(fields: "id") {
    id: ID!
    name: String!
    projectId: ID!
    parentTeamId: ID
    createdAt: String!
    members(input: PaginationInput): [TeamMember!]!
    tasks(input: PaginationInput): [Task!]!
}

type TeamMember {
    user: User!
    createdAt: String!
}

type Task @key(fields: "id") {
    id: ID!
    projectId: ID!
    parentTaskId: ID
    rootId: ID
    path: String!
    createdBy: ID!
    title: String!
    description: String
    assignedTeam: Team
    assignedTeamMember: User
    status: String!
    lexoRank: String!
    version: Int!
    createdAt: String!
    updatedAt: String
}
