const { h1, h2, body, numberedRuns, run } = require('../utils');

module.exports = function getChapter1_1() {
  return [
    // ══════════════════════════════════════════════════════════════
    // CHAPTER 1: INTRODUCTION
    // ══════════════════════════════════════════════════════════════
    h1("1. INTRODUCTION"),

    h2("1.1 Problem Definition"),
    body("As modern organizations scale their operations, project management demands have evolved from simple, flat to-do lists into highly complex, interconnected workflows involving hundreds of cross-functional teams. Enterprise projects are no longer linear; they consist of massively nested sub-tasks, strict multi-node dependency graphs, and multi-stage approval processes. To manage this complexity efficiently, software orchestration tools must provide instant visual feedback to stakeholders while guaranteeing absolute data integrity across thousands of concurrent users."),
    body("Designing software applications capable of handling massive scale—targeting upwards of 10,000 Requests Per Second (RPS)—presents a severe engineering challenge. Traditional monolithic CRUD (Create, Read, Update, Delete) architectures rapidly degrade under these conditions. In a purely synchronous environment, executing a complex business operation—such as deleting a high-level task that possesses thousands of descendants, or assigning a large group of members to a workflow—forces the database to execute massive cascading updates. These operations require long-lived row-level or table-level locks. Consequently, concurrent reads and writes from other users are blocked, transaction queues fill up, and the system experiences cascading timeout failures."),
    body("Furthermore, modern clients demand real-time interactivity. When a task status is updated by one user, other stakeholders viewing the same dashboard expect that update to reflect instantly on their screen without necessitating a manual page refresh. Implementing real-time synchronization at an enterprise scale introduces the infamous \"Fan-Out\" problem: if 1,000 users are concurrently connected to the application, broadcasting every single system event to every connected client saturates the internal network and overwhelms end-user devices with irrelevant data payloads."),
    body("According to the CAP theorem formulated by Eric Brewer, a distributed system can simultaneously provide only two of the following three guarantees: Consistency, Availability, and Partition Tolerance. In traditional relational architectures, design philosophies are heavily skewed towards Strong Consistency, ensuring that ACID (Atomicity, Consistency, Isolation, Durability) transactions block entirely until they are globally committed. However, under extreme load, prioritizing Strong Consistency inevitably sacrifices Availability, leading to system outages."),
    body("To achieve massive throughput without crippling the infrastructure, there is a fundamental need to shift away from blocking synchronous processing. The core problem addressed in this thesis is the design, implementation, and evaluation of a highly scalable workflow orchestration engine. This engine must mitigate database write amplification, prevent distributed race conditions through intelligent concurrency controls, and provide targeted real-time updates without compromising the core database stability or network bandwidth."),

    h2("1.2 Project Overview"),
    body("The primary objective of this thesis is to design and implement Taskinator, a full-stack workflow orchestration platform engineered specifically to achieve extreme throughput and zero-loss event processing. The system offers a comprehensive suite of tools designed to handle deeply nested task hierarchies, real-time multi-user collaboration, and complex event-driven automation."),
    body("Taskinator fundamentally prioritizes Availability and Partition Tolerance (AP in the CAP theorem context). To achieve a massive throughput of 10,000 RPS, the system deliberately sacrifices strict, immediate Consistency in favor of Eventual Consistency. This intentional architectural trade-off forms the foundation of the system's design, allowing the primary data store to process writes rapidly while offloading expensive side-effects to asynchronous background workers."),
    body("The core features and architectural milestones of the system include:"),
    numberedRuns([run("Project & Team Management Contexts: ", true), run("Organizations can create distinct operational projects and organize users into nested Team hierarchies. A sophisticated Custom Closure Table pattern ensures that access control calculations and bulk assignments execute rapidly in O(1) time complexity, natively respecting deep inheritance rules without requiring expensive recursive queries during runtime.")], "n1"),
    numberedRuns([run("Infinite Task Reachability Graph: ", true), run("Users are not constrained by flat lists; they can create infinitely nested tasks and sub-tasks, establishing complex multi-parent dependencies. These dependencies are represented visually through an interactive, heavily optimized React Task Graph, enabling intuitive navigation of massive project structures.")], "n1"),
    numberedRuns([run("Event-Driven Asynchrony (EDA): ", true), run("Critical user operations—such as creating tasks or establishing links—remain strictly synchronous to provide immediate HTTP responses and positive user feedback. However, computationally expensive side effects—such as aggregate count updates, notifications, and closure table path matrix calculations—are atomically offloaded to an Apache Kafka message broker for deferred processing.")], "n1"),
    numberedRuns([run("Zero-Fan-Out Real-Time Synchronization: ", true), run("A highly targeted, memory-resident Redis routing layer maps active user sessions to specific server instances. This ensures that Server-Sent Events (SSE) are pushed exclusively to the specific clients who are actively viewing the mutated data, reducing network fan-out from O(N) to near O(1).")], "n1"),
    numberedRuns([run("Rule-Based Automation & Triggers: ", true), run("The system incorporates a deterministic \"IF-THEN-CLEANUP\" engine that reacts natively to domain events. This handles complex workflows, such as \"Parent Guard Triggers,\" which automatically prevent parent tasks from being marked as completed if any descendant sub-tasks remain pending, preserving logical integrity across the graph.")], "n1"),
  ];
};
