const { h1, h2, body, numberedRuns, run } = require('../utils');

module.exports = function getChapter1_1() {
  return [
    // ══════════════════════════════════════════════════════════════
    // CHAPTER 1: INTRODUCTION
    // ══════════════════════════════════════════════════════════════
    h1("1. INTRODUCTION"),

    h1("1. INTRODUCTION"),

    h2("1.1 Problem Definition in High-Scale Orchestration"),
    body("As modern organizations scale their operations to meet the demands of a globalized economy, the requirements for project management and task orchestration have evolved from simple, flat to-do lists into highly complex, interconnected digital ecosystems. Contemporary enterprise projects are no longer linear sequences of activities; instead, they consist of massively nested hierarchies, strict multi-node dependency graphs, and multi-stage, cross-functional approval processes. To manage this systemic complexity efficiently, software orchestration tools must provide instantaneous visual feedback to stakeholders while simultaneously guaranteeing absolute data integrity and referential consistency across thousands of concurrent actors."),
    body("The engineering of software applications capable of sustaining massive scale—specifically targeting upwards of 10,000 Requests Per Second (RPS)—presents a severe and multi-dimensional technical challenge. Traditional monolithic CRUD (Create, Read, Update, Delete) architectures, which rely on synchronous relational database transactions for all operational state changes, rapidly degrade under these conditions. In a purely synchronous environment, executing a complex business operation—such as the deletion of a high-level project node that possesses thousands of descendants, or the bulk assignment of members to a recursive workflow—forces the database engine to execute massive cascading updates. These operations require long-lived row-level or table-level locks, leading to a state of 'Write Amplification' where a single user action triggers a exponential sequence of internal database operations."),
    body("The consequence of this synchronous blocking is catastrophic at scale. Concurrent read and write operations from other users are queued behind these locks, leading to increased latency, transaction log saturation, and ultimately, system-wide timeout failures. This phenomenon is exacerbated in 'Collaborative' environments where the state of the system is in constant flux, and the cost of maintaining a consistent view across all distributed instances becomes the primary bottleneck."),
    body("Furthermore, modern enterprise users demand a level of real-time interactivity that mimics local desktop applications. When a task status is transitioned by one user, every other stakeholder viewing the same project dashboard expects that update to reflect instantaneously on their screen without the cognitive friction of a manual page refresh. Implementing such real-time synchronization at an enterprise scale introduces the infamous 'Fan-Out Problem'. If 1,000 users are concurrently connected to a project, a single mutation event could theoretically require 1,000 outgoing network broadcasts. Without a targeted routing strategy, this 'Event Storm' saturates the internal network backbone and overwhelms end-user devices with irrelevant or duplicate data payloads, leading to a degraded user experience and increased infrastructure costs."),
    body("According to the CAP theorem formulated by Eric Brewer, a distributed system can simultaneously provide only two of the following three guarantees: Consistency, Availability, and Partition Tolerance. In traditional relational architectures, design philosophies are heavily skewed towards 'Strong Consistency', ensuring that ACID (Atomicity, Consistency, Isolation, Durability) transactions block the execution thread until the state change is globally committed. However, under extreme throughput requirements, prioritizing Strong Consistency inevitably sacrifices Availability, as the system becomes unresponsive during high-contention periods. There is, therefore, a fundamental architectural need to transition towards models of 'Eventual Consistency' and 'Asynchronous Persistence' to maintain high availability without compromising the underlying data durability."),
    body("The core problem addressed in this thesis is the design, implementation, and rigorous evaluation of a high-throughput, event-driven task orchestration engine. This engine must mitigate database write amplification through intelligent batching, prevent distributed race conditions through optimistic concurrency controls, and provide highly targeted real-time updates through a zero-fan-out routing architecture—all while maintaining a sub-50ms response time for primary user interactions."),

    h2("1.2 Project Overview and Objectives"),
    body("The primary objective of this research is to design and implement 'Taskinator', a full-stack project orchestration platform engineered from the ground up to achieve extreme throughput and zero-loss event processing. Unlike traditional project management tools that are built on top of generic CRUD frameworks, Taskinator is constructed around a specialized event-driven core that decouples the act of data persistence from the processing of its associated side-effects."),
    body("Taskinator fundamentally prioritizes 'Availability' and 'Partition Tolerance' (the AP side of the CAP theorem) to ensure that the platform remains responsive even under conditions of extreme network jitter or storage layer saturation. By deliberately transitioning from immediate 'Strong Consistency' to a model of 'Eventual Consistency' for non-critical aggregate data, the system achieves a massive throughput capability of 10,000 RPS on modest infrastructure hardware."),
    body("The technical objectives and architectural milestones achieved in this project include:"),
    
    numberedRuns([run("Highly Optimized Hierarchical Modeling: ", true), run("Implementing a custom Closure Table pattern for project and team hierarchies. This ensures that permission checks, member inheritance, and bulk data migrations execute with O(1) or O(Log N) complexity, avoiding the performance pitfalls of recursive SQL queries at runtime.")], "n1"),
    
    numberedRuns([run("Reactive Task Graph Engine: ", true), run("Developing a high-performance, SVG-based Task Graph visualization using D3.js and React. This engine provides users with an intuitive, interactive canvas to navigate and manipulate complex DAG (Directed Acyclic Graph) structures, with support for real-time dependency highlighting and path discovery.")], "n1"),
    
    numberedRuns([run("Transactional Outbox and Event-Driven Asynchrony: ", true), run("The integration of the 'Transactional Outbox' pattern using PostgreSQL wCTE (Write Common Table Expressions). This guarantees the atomic persistence of business state and its corresponding event notification, ensuring that the system's asynchronous background workers—such as the Smart Aggregator and Reachability Processor—always operate on a consistent and authoritative event log.")], "n1"),
    
    numberedRuns([run("Zero-Fan-Out Real-Time Synchronization: ", true), run("The implementation of a targeted real-time routing layer using Redis Pub/Sub and Server-Sent Events (SSE). By maintaining an ephemeral mapping of active project IDs to specific server instances, the system achieves 'targeted delivery', where updates are only transmitted to relevant stakeholders, minimizing network overhead.")], "n1"),
    
    numberedRuns([run("Atomic Rule-Based Automation: ", true), run("A deterministic 'Trigger and Cleanup' engine that reacts to domain events in real-time. This includes 'Safety-Gated' recursion control to prevent infinite automation loops while enforcing complex business rules, such as automatic parent task completion based on child state.")], "n1"),
  ];
};
