const { h1, h2, body, emptyLine, imgPlaceholder, figCaption, codeLine, pageBreak } = require('../utils');

module.exports = function getChapter4() {
  return [
    // ══════════════════════════════════════════════════════════════
    // CHAPTER 4: EVENT-DRIVEN PIPELINE
    // ══════════════════════════════════════════════════════════════
    h1("4. EVENT-DRIVEN PIPELINE (EDA) IMPLEMENTATION"),
    body("The foundational backbone of Taskinator is its highly tuned Event-Driven Architecture (EDA). This architecture rejects synchronous side-effect processing entirely, instead utilizing pervasive batching strategies that begin all the way upstream at the producer level and carry through to the downstream consumers."),

    h2("4.1 The Transactional Outbox Pattern & wCTE"),
    body("A classic, well-documented failure mode in distributed systems occurs when a database transaction successfully commits, but the application Node.js process crashes milliseconds before publishing the resulting domain event to Apache Kafka. This creates a ghost state: the data exists in the database, but downstream systems (analytics, search indexing, real-time UIs) are completely unaware, leaving the system permanently inconsistent."),
    body("Taskinator utilizes the Transactional Outbox Pattern to guarantee absolute atomic writes without dual-write failures."),
    emptyLine(),
    imgPlaceholder("Figure 4.1: Transactional Outbox Workflow using wCTE"),
    figCaption("Figure 4.1: Transactional Outbox Workflow using wCTE"),
    body("While traditional Outbox implementations execute multiple sequential SQL INSERT statements within a BEGIN...COMMIT block, Taskinator optimizes this using PostgreSQL's Data-Modifying Common Table Expressions (wCTE). A single SQL query uses WITH clauses to insert the business data and immediately insert the serialized JSON payload into the outbox_events table simultaneously:"),
    codeLine("WITH inserted_task AS (", 120),
    codeLine("  INSERT INTO project_task (id, fk_project_id, title, status, version)"),
    codeLine("  VALUES ($1, $2, $3, $4, 1)"),
    codeLine("  RETURNING *"),
    codeLine("),"),
    codeLine("inserted_event AS ("),
    codeLine("  INSERT INTO outbox_events (aggregate_id, event_type, payload)"),
    codeLine("  VALUES ("),
    codeLine("    (SELECT id FROM inserted_task),"),
    codeLine("    'TASK_CREATED',"),
    codeLine("    jsonb_build_object('id', (SELECT id FROM inserted_task), 'status', $4)"),
    codeLine("  )"),
    codeLine(")"),
    codeLine("SELECT * FROM inserted_task;", 0, 120),
    body("If the transaction rolls back due to a constraint violation or a server crash mid-flight, both the task and the event are safely discarded by the database engine. They succeed or fail as a singular, indivisible unit of work, requiring only one network roundtrip."),

    h2("4.2 Concurrent Outbox Relays: Mitigating the Thundering Herd"),
    body("Traditional outbox relays utilize primitive setInterval loops to aggressively poll the database for new events. At 10,000 RPS, this creates severe database CPU load even when the system is idle."),
    body("Taskinator discards polling entirely in favor of reactivity. The Outbox Relay connects via the pg driver and executes a persistent LISTEN outbox_event_notification command. When the aforementioned wCTE commits, PostgreSQL natively pushes a highly efficient, lightweight notification through the socket."),
    body("However, in a horizontally scaled Kubernetes environment, this reactivity creates a catastrophic \"Thundering Herd\" problem: 50 different relay pods wake up simultaneously to grab the exact same batch of events."),
    emptyLine(),
    imgPlaceholder("Figure 4.2: Concurrent Outbox Polling: Mitigating the Thundering Herd with SKIP LOCKED"),
    figCaption("Figure 4.2: Concurrent Outbox Polling: Mitigating the Thundering Herd with SKIP LOCKED"),
    body("To solve this, Taskinator utilizes the advanced FOR UPDATE SKIP LOCKED database directive. When the notification fires, Pod 1 executes SELECT ... FOR UPDATE SKIP LOCKED LIMIT 100. It immediately acquires a row-level lock on rows 1 through 100. Milliseconds later, Pod 2 executes the exact same query. Because of the SKIP LOCKED directive, the PostgreSQL engine instructs Pod 2 to completely bypass rows 1-100 without waiting for the lock to release. Pod 2 instead reads and instantly locks rows 101 through 200."),
    body("The result is massive, lock-free concurrent throughput across dozens of pods without polling loops, database deadlocks, or duplicate event publishing."),

    h2("4.3 Smart Batch Aggregation & Semantic Folding"),
    body("Pushing millions of events efficiently into Kafka is entirely useless if the downstream consumers cannot process them rapidly enough. Naive consumers execute one database transaction per incoming Kafka event. At 10k RPS, executing 10,000 sequential UPDATE transactions crushes the database connection pool."),
    body("Taskinator introduces the Smart Batch Aggregator."),
    emptyLine(),
    imgPlaceholder("Figure 4.3: Smart Batch Aggregator Data Flow and Semantic Folding"),
    figCaption("Figure 4.3: Smart Batch Aggregator Data Flow and Semantic Folding"),
    body("The Kafka consumer receives a massive batch of events (e.g., batchSize: 5000) and buffers them chronologically. It loops over the events strictly in memory. If the aggregator detects 50 \"Task Created\" events and 20 \"Task Deleted\" events pertaining to the exact same project within the batch window, it does not execute 70 individual SQL updates. Instead, it executes a Semantic Folding Algorithm to calculate a net mathematical delta (+30). It then executes a single, batched database update to the denormalized project.task_count metric."),
    codeLine("// Semantic Folding Algorithm Snippet", 120),
    codeLine("const deltas = new Map<string, number>();"),
    codeLine(""),
    codeLine("for (const event of batch) {"),
    codeLine("  if (event.type === 'TASK_CREATED') {"),
    codeLine("    deltas.set(event.projectId, (deltas.get(event.projectId) || 0) + 1);"),
    codeLine("  } else if (event.type === 'TASK_DELETED') {"),
    codeLine("    deltas.set(event.projectId, (deltas.get(event.projectId) || 0) - 1);"),
    codeLine("  }"),
    codeLine("}"),
    codeLine(""),
    codeLine("// Execute folded updates"),
    codeLine("await db.transaction().execute(async (trx) => {"),
    codeLine("  for (const [projectId, delta] of deltas) {"),
    codeLine("    if (delta !== 0) {"),
    codeLine("      await trx.updateTable('project')"),
    codeLine("        .set((eb) => ({ task_count: eb('task_count', '+', delta) }))"),
    codeLine("        .where('id', '=', projectId)"),
    codeLine("        .execute();"),
    codeLine("    }"),
    codeLine("  }"),
    codeLine("});", 0, 120),
    body("By partitioning the Kafka topic strictly by projectId, the system guarantees that related events land on the same consumer thread, making in-memory folding highly effective and drastically reducing database write amplification."),

    h2("4.4 Chunked Self-Signaling Deletion (The Bubbling Effect)"),
    body("In hierarchical systems, deleting a root node that possesses 50,000 descendants via a synchronous SQL ON DELETE CASCADE command will acquire an exclusive database table lock for several seconds. Taskinator circumvents this by implementing Declarative Signalling and Self-Chunking."),
    emptyLine(),
    imgPlaceholder("Figure 4.4: Chunked Self-Signaling Deletion (\"The Bubbling Effect\")"),
    figCaption("Figure 4.4: Chunked Self-Signaling Deletion (\"The Bubbling Effect\")"),
    body("When a user deletes a large project, the API does not execute a SQL DELETE on the tasks. Instead, it merely emits a declarative signal: PROJECT_DELETED into the Outbox. A specialized Background Listener picks up this signal and queries a very small chunk using explicit limits: SELECT id FROM project_task WHERE fk_project_id = X LIMIT 2000. The Listener deletes only those 2000 rows."),
    body("If more rows remain in the project, the Listener deliberately emits a new, identical self-signal (PROJECT_DELETED) back into the outbox. This recursively \"bubbles\" through the message queue until the table is completely purged. By enforcing strict LIMIT 2000 bounds on every operation, the maximum duration of a database lock never exceeds a few milliseconds, ensuring the application remains 100% available to all other users during massive cleanup operations."),

    pageBreak(),
  ];
};
