const { h1, h2, body, emptyLine, imgPlaceholder, figCaption } = require('../utils');

module.exports = function getChapter6_1() {
  return [
    h1("6. FRONTEND ARCHITECTURE AND REAL-TIME SYNCHRONIZATION"),
    body("Pushing data to the client efficiently is only half the battle in a real-time collaborative system. If the client simply triggers a full-page data refetch upon receiving a Server-Sent Event (SSE) payload, the backend database will be instantly overwhelmed by redundant read queries, defeating the purpose of the Event-Driven Architecture entirely. Taskinator's frontend is engineered to surgically inject updates directly into the in-memory cache, achieving O(1) rendering complexity."),

    h2("6.1 The React Task Graph and D3.js Visualization"),
    body("To represent the deeply nested Directed Acyclic Graphs (DAGs) generated by the Reachability Engine, traditional list-based HTML UI components are fundamentally inadequate. Complex multi-parent dependencies require spatial visualization. Taskinator employs a custom visualization engine utilizing React 18 and D3.js."),
    emptyLine(),
    imgPlaceholder("Figure 6.1: Frontend UI State Machine"),
    figCaption("Figure 6.1: Frontend UI State Machine"),
    body("D3.js is universally recognized for its powerful mathematical layout algorithms (e.g., d3.hierarchy, d3.dag, and d3.tree). However, traditional D3 implementations forcefully mutate the Document Object Model (DOM) directly, competing with React's virtual DOM reconciliation cycle and causing severe layout thrashing."),
    body("Taskinator strictly delegates all DOM rendering exclusively to React. D3 is relegated to a pure mathematical calculation role. It calculates the absolute (x, y) SVG coordinates of the individual task nodes and computes the complex bezier curves for the linking edges purely in memory. React then consumes this structured data array, mapping over it to rapidly render pure, declarative SVG <circle> and <path> components."),
    body("This hybrid approach prevents costly browser layout reflows and allows React's Concurrent Mode to interrupt and prioritize rendering frames smoothly, guaranteeing a consistent 60 Frames Per Second (FPS) visual experience even when manipulating and panning across a canvas containing thousands of simultaneous SVG nodes."),
  ];
};
