const { h2, h3, body, codeLine, pageBreak } = require('../utils');

module.exports = function getChapter6_4() {
  return [
    h2("6.4 Declarative SVG Rendering: React & D3.js Integration"),
    body("To avoid the DOM thrashing typically associated with imperative D3.js manipulations, the frontend completely separates the mathematical layout engine from the rendering engine. D3 is used strictly as a pure function to compute SVG coordinates, while React is used to declaratively mount the elements into the browser DOM."),

    h3("6.4.1 Layout Calculation and Rendering Code"),
    body("The following React code excerpt illustrates the implementation of the TaskGraph component. The raw, flat array of nodes and edges retrieved from the GraphQL getTaskGraph query is parsed into a d3.stratify() hierarchy. A customized d3.dag() layout generator calculates the absolute 'x' and 'y' properties for every node."),
    
    codeLine("import { useMemo } from 'react';", 120),
    codeLine("import { dagStratify, sugiyama } from 'd3-dag';"),
    codeLine(""),
    codeLine("export const TaskGraph = ({ rawTasks, edges }) => {"),
    codeLine("  // 1. Pure Mathematical Calculation (Memoized to prevent recalculation)"),
    codeLine("  const { nodes, links } = useMemo(() => {"),
    codeLine("    const dag = dagStratify()(rawTasks, edges);"),
    codeLine("    const layout = sugiyama().nodeSize([150, 100]);"),
    codeLine("    layout(dag); // Mutates 'dag' with x,y coordinates"),
    codeLine("    "),
    codeLine("    return {"),
    codeLine("      nodes: dag.descendants(),"),
    codeLine("      links: dag.links()"),
    codeLine("    };"),
    codeLine("  }, [rawTasks, edges]);"),
    codeLine(""),
    codeLine("  // 2. Pure Declarative Rendering (Zero D3 DOM Manipulation)"),
    codeLine("  return ("),
    codeLine("    <svg width=\"100%\" height=\"100%\" viewBox=\"0 0 1000 800\">"),
    codeLine("      <g className=\"edges\">"),
    codeLine("        {links.map(link => ("),
    codeLine("          <path "),
    codeLine("            key={`${link.source.id}-${link.target.id}`}"),
    codeLine("            d={generateBezier(link)} // Custom bezier curve generator"),
    codeLine("            stroke=\"#CBD5E1\""),
    codeLine("            fill=\"none\""),
    codeLine("          />"),
    codeLine("        ))}"),
    codeLine("      </g>"),
    codeLine("      <g className=\"nodes\">"),
    codeLine("        {nodes.map(node => ("),
    codeLine("          <circle "),
    codeLine("            key={node.data.id}"),
    codeLine("            cx={node.x}"),
    codeLine("            cy={node.y}"),
    codeLine("            r={24}"),
    codeLine("            fill={node.data.status === 'DONE' ? '#10B981' : '#3B82F6'}"),
    codeLine("          />"),
    codeLine("        ))}"),
    codeLine("      </g>"),
    codeLine("    </svg>"),
    codeLine("  );"),
    codeLine("};", 0, 120),
    
    h3("6.4.2 Performance Implications"),
    body("By utilizing React's useMemo hook, the heavy sugiyama layout algorithm is only executed when the underlying structural graph data (rawTasks or edges) actually mutates. If a task simply changes its status (e.g., from 'TODO' to 'DONE') via the SSE pipeline, the reference arrays remain identical. React bypasses the expensive D3 math recalculation entirely and proceeds directly to the rendering phase, where it executes a highly localized DOM patch to alter the SVG <circle> fill color. This architecture guarantees a stable 60 FPS visual experience regardless of event throughput."),

    pageBreak(),
  ];
};
